#!/usr/bin/env python3
"""Merge a PRIVATE reviewer-policy overlay over the tracked generic base.

Why this exists
---------------
`extensions/oasis-reviewer/policy/reviewer-policy.json` is committed to a public
repository, so it must contain NO deployment-specific content: no real bot
names, no per-bot access scopes, no operator identity. It ships the fleet-wide
security baseline only, with `botAliases` and `per_bot` deliberately empty.

A real deployment keeps that content in a private overlay that is never
committed, and merges it over the base at install/boot time. This script is
that merge step.

Contract
--------
BASE     tracked, public, generic. Supplies `constitution.fleet` and
         `hard.fleet` — the security baseline. Improvements to the baseline
         flow to every deployment through normal updates.
OVERLAY  private, gitignored. Supplies `botAliases`, `constitution.per_bot`,
         and `hard.per_bot`. MAY also override the fleet sections if a
         deployment needs a different baseline; if it omits them, the base
         wins.
OUT      generated, gitignored. Bind-mount this over the image's copy of
         reviewer-policy.json at container start.

Usage
-----
    scripts/reviewer-policy-merge.py BASE OVERLAY OUT

Fails loudly rather than emitting a partial policy. A reviewer policy that
silently loses its per-bot rules is worse than one that refuses to build: the
bots would come up on the fleet baseline with no per-bot escalations, and
nothing would report that the rules had gone missing.
"""

import json
import sys


def die(msg: str) -> None:
    print(f"[reviewer-policy-merge] FATAL: {msg}", file=sys.stderr)
    raise SystemExit(1)


def load(path: str, what: str) -> dict:
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except FileNotFoundError:
        die(f"{what} not found: {path}")
    except json.JSONDecodeError as exc:
        die(f"{what} is not valid JSON ({path}): {exc}")


def main() -> None:
    if len(sys.argv) != 4:
        die("usage: reviewer-policy-merge.py BASE OVERLAY OUT")
    base_path, overlay_path, out_path = sys.argv[1:4]

    base = load(base_path, "base policy")
    overlay = load(overlay_path, "private overlay")

    merged = {
        "_doc": base.get("_doc", ""),
        "_generated": (
            "GENERATED by scripts/reviewer-policy-merge.py — do not edit by hand "
            "and do not commit. Edit the private overlay instead."
        ),
        "botAliases": {**base.get("botAliases", {}), **overlay.get("botAliases", {})},
    }

    for section in ("constitution", "hard"):
        b = base.get(section, {})
        o = overlay.get(section, {})
        merged[section] = {
            # Overlay may override the baseline; otherwise the tracked base wins.
            "fleet": o["fleet"] if "fleet" in o else b.get("fleet"),
            # per_bot is overlay-owned: that is the whole point of the split.
            "per_bot": {**b.get("per_bot", {}), **o.get("per_bot", {})},
        }
        if merged[section]["fleet"] is None:
            die(f"neither base nor overlay defines {section}.fleet — refusing to emit a policy with no baseline")

    n_bots = len(merged["constitution"]["per_bot"])
    if n_bots == 0:
        die(
            "merged policy has zero per-bot entries. That is almost certainly a wrong "
            "overlay path, and it would silently drop every per-bot escalation rule."
        )

    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(merged, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    # Report bot COUNT and KEYS only. Never echo policy text: it can carry
    # deployment-specific detail, which is exactly what this split protects.
    print(
        f"[reviewer-policy-merge] wrote {out_path}: "
        f"{n_bots} per-bot entries ({', '.join(sorted(merged['constitution']['per_bot']))}), "
        f"{len(merged['botAliases'])} aliases"
    )


if __name__ == "__main__":
    main()
